"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
# Pour le refresh/rotation de tokens
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_list(name, default, aliases=()):
    """Lit une liste separee par des virgules depuis l'environnement.

    `aliases` permet de rester compatible avec les noms deja configures sur la
    plateforme de deploiement (Dokploy definit `ALLOWED_HOSTS`, `CORS_ALLOWED_ORIGINS`
    et `CSRF_TRUSTED_ORIGINS` sans prefixe) : sans cela, la configuration de
    l'operateur serait silencieusement ignoree au profit des valeurs par defaut.
    """
    for key in (name, *aliases):
        raw = os.environ.get(key)
        if raw:
            return [item.strip() for item in raw.split(",") if item.strip()]
    return list(default)


def with_scheme(origins, default_scheme="https"):
    """Prefixe d'un schema les origines qui n'en ont pas.

    `CSRF_TRUSTED_ORIGINS` et `CORS_ALLOWED_ORIGINS` exigent un schema
    (`https://exemple.cd`). Les variables d'environnement en place contiennent
    des noms d'hote nus, qui provoqueraient une erreur de configuration au
    demarrage : on les normalise plutot que d'imposer une reecriture cote infra.
    """
    normalized = []
    for origin in origins:
        if "://" in origin:
            normalized.append(origin)
        else:
            normalized.append(f"{default_scheme}://{origin}")
    return normalized


# SECURITY WARNING: don't run with debug turned on in production!
# Par defaut False : un deploiement qui oublie la variable reste sur la config sure.
DEBUG = os.environ.get("DEBUG", "False") == "True"

# SECURITY WARNING: keep the secret key used in production secret!
# En production la variable DJANGO_SECRET_KEY est obligatoire ; en dev une cle
# jetable est generee au demarrage pour ne pas bloquer le developpeur.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if not DEBUG:
        raise RuntimeError(
            "DJANGO_SECRET_KEY est obligatoire lorsque DEBUG=False. "
            "Generez une cle avec la commande : "
            "python -c 'from django.core.management.utils import get_random_secret_key; "
            "print(get_random_secret_key())'"
        )
    from django.core.management.utils import get_random_secret_key

    SECRET_KEY = get_random_secret_key()

DEFAULT_ALLOWED_HOSTS = [
    "bibliotech.cd",
    "admin.bibliotech.cd",
    "api.bibliotech.cd",
    "dev.bibliotech.cd",
    "dev-api.bibliotech.cd",
    "dev-admin.bibliotech.cd",
]
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", DEFAULT_ALLOWED_HOSTS, aliases=("ALLOWED_HOSTS",))
if DEBUG:
    # Confort de developpement : l'API reste joignable en local sans configuration.
    ALLOWED_HOSTS += ["localhost", "127.0.0.1", "[::1]", "testserver"]

AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    # Necessaire pour que ROTATE_REFRESH_TOKENS / BLACKLIST_AFTER_ROTATION
    # et la deconnexion revoquent reellement les refresh tokens.
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
    'users',
    'school'
]

MIDDLEWARE = [
    # CorsMiddleware doit venir avant CommonMiddleware pour que les en-tetes CORS
    # soient poses meme sur les reponses generees tot (redirections notamment).
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'bibliotech_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'prod_postgres'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

if DEBUG:
    # Dossier des fichiers statiques "bruts" pour le dev (ignore s'il n'existe pas,
    # sinon Django remonte un avertissement staticfiles.W004 au demarrage).
    STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").is_dir() else []
    # Pas de STATIC_ROOT ni de Whitenoise en dev
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    # Production
    STATIC_ROOT = BASE_DIR / "staticfiles"
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # HSTS : desactive par defaut car un navigateur memorise l'en-tete pendant
    # toute sa duree et refusera ensuite le HTTP sur le domaine — une valeur
    # trop longue posee trop tot est difficile a annuler. Montee progressive
    # recommandee : 3600, puis 86400, puis 31536000 une fois le HTTPS eprouve.
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "0"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = (
        os.environ.get("DJANGO_HSTS_INCLUDE_SUBDOMAINS", "False") == "True"
    )
    SECURE_HSTS_PRELOAD = os.environ.get("DJANGO_HSTS_PRELOAD", "False") == "True"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Racine des pages de livres : un dossier par livre (<uuid>/content_01.txt, ...),
# chaque fichier contenant une image de page encodee en base64.
# Chemin absolu base sur BASE_DIR pour ne pas dependre du repertoire courant.
BOOKS_CONTENT_ROOT = Path(
    os.environ.get("BOOKS_CONTENT_ROOT", BASE_DIR / "books_content")
)

# Cache disque des vignettes de couverture. Place hors de BOOKS_CONTENT_ROOT,
# qui peut etre monte en lecture seule.
BOOKS_THUMBNAIL_ROOT = Path(
    os.environ.get("BOOKS_THUMBNAIL_ROOT", BASE_DIR / ".thumbnails")
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CSRF_TRUSTED_ORIGINS = with_scheme(
    env_list(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        [
            "https://bibliotech.cd",
            "https://admin.bibliotech.cd",
            "https://api.bibliotech.cd",
            "https://dev.bibliotech.cd",
            "https://dev-api.bibliotech.cd",
            "https://dev-admin.bibliotech.cd",
        ],
        aliases=("CSRF_TRUSTED_ORIGINS",),
    )
)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Django REST Framework config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

# CORS config (frontend Next.js servi sur un autre domaine)
CORS_ALLOWED_ORIGINS = with_scheme(
    env_list(
        "DJANGO_CORS_ALLOWED_ORIGINS",
        [
            "https://bibliotech.cd",
            "https://admin.bibliotech.cd",
            "https://api.bibliotech.cd",
            "https://dev.bibliotech.cd",
            "https://dev-api.bibliotech.cd",
            "https://dev-admin.bibliotech.cd",
            "http://localhost:3000",
        ],
        aliases=("CORS_ALLOWED_ORIGINS",),
    )
)


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
