# Generated by Django 5.2.7 on 2025-10-19 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=500, unique=True)),
                (
                    "publish_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        max_length=10,
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("page", models.PositiveIntegerField()),
                (
                    "book_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("epub", "EPUB"),
                            ("audiobook", "Audiobook"),
                            ("paper", "Paper"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
