# Generated by Django 5.2.7 on 2025-10-19 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        db_column="book_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="school.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Page",
                "verbose_name_plural": "Book Pages",
                "ordering": ["order"],
            },
        ),
    ]
