# Generated by Django 5.2.7 on 2025-10-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_bookpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookpage",
            name="title",
            field=models.TextField(),
        ),
    ]
