# Generated by Django 5.2.7 on 2025-10-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_alter_bookpage_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="allowed_classes",
            field=models.ManyToManyField(
                blank=True, related_name="accessible_books", to="school.class"
            ),
        ),
    ]
