# Generated by Django 5.2.10 on 2026-01-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_book_allowed_classes"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_file",
            field=models.FileField(blank=True, null=True, upload_to="books/files/"),
        ),
    ]
