# Generated by Django 5.2.10 on 2026-01-08 14:20

import school.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_book_book_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_file",
            field=models.FileField(
                blank=True, null=True, upload_to=school.models.book_file_upload_path
            ),
        ),
    ]
