# Generated by Django 5.2.10 on 2026-01-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_alter_book_book_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="already_process",
            field=models.BooleanField(default=False),
        ),
    ]
