# Generated by Django 5.2.10 on 2026-01-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0008_book_already_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="processing_error",
            field=models.TextField(
                blank=True,
                help_text="Erreur de traitement (format Markdown)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="page",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
