# Generated by Django 5.2.10 on 2026-01-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0009_book_processing_error_alter_book_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="already_process",
        ),
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
