# Generated by Django 5.2.17 on 2026-08-15 22:28

from django.db import migrations, models


def set_epub_cover_page(apps, schema_editor):
    """Les EPUB deja importes passent sur la couverture generee.

    Leur conversion en images commence par des pages blanches : servir la
    page 1 revient a afficher un rectangle vide.
    """
    Book = apps.get_model('school', 'Book')
    Book.objects.filter(book_format='epub').update(cover_page=0)


def restore_epub_cover_page(apps, schema_editor):
    Book = apps.get_model('school', 'Book')
    Book.objects.filter(book_format='epub').update(cover_page=1)


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_book_already_process_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_page',
            field=models.PositiveIntegerField(default=1, help_text='Numero de la page a utiliser comme couverture. 0 pour afficher une couverture generee automatiquement.', verbose_name='Page de couverture'),
        ),
        migrations.RunPython(set_epub_cover_page, restore_epub_cover_page),
    ]
