# Generated by Django 5.2.10 on 2026-01-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0010_remove_book_already_process_book_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="download_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="download_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
