# Generated by Django 5.2.17 on 2026-09-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0011_book_cover_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="Nom"),
                ),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Les valeurs les plus basses apparaissent en premier.",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categorie",
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="books",
                to="school.category",
                verbose_name="Categories",
            ),
        ),
    ]
