# Generated by Django 5.2.17 on 2026-08-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_book_cover_page'),
        ('school', '0011_book_download_token_book_download_token_expires_at'),
    ]

    operations = [
    ]
