# Generated by Django 5.2.17 on 2026-09-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0012_merge_20260815_2236"),
        ("school", "0013_seed_categories"),
    ]

    operations = []
